# Домашнее задание 1

#### Воронцов Александр Александрович

## 1. Какие ещё существуют коды типов?

#### Помимо i (I) - знаковый (беззнаковый) int, в библиотеке array существуют ещё такие коды типов, как: b (B) - знаковый (беззнаковый) char, h (H) - знаковый (беззнаковый) short, l (L) - знаковый (беззнаковый) long, q (Q) - знаковый (беззнаковый) long long, f - float, d - double, u - Unicode char.

## 2. Напишите код, подобный приведенному выше, но с другим типом

In [1]:
import array
import sys

a1 = array.array('u', ['a', 'b', 'c'])
print(sys.getsizeof(a1))
print(type(a1))

92
<class 'array.array'>


## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

In [2]:
import numpy as np

a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1

In [3]:
a = np.random.uniform(0, 1, 5)
print(a)

[0.10515843 0.08399986 0.07860613 0.24327211 0.46952927]


## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1

In [4]:
a = np.random.normal(0, 1, 5)
print(a)

[ 0.39375763  0.21782695 -0.83806173  1.46169224 -0.203463  ]


## 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)

In [5]:
a = np.random.randint(10, size=5)
print(a)

[8 1 7 6 5]


## 7. Написать код для создания срезов массива 3 на 4
## - первые две строки и три столбца
## - первые три строки и второй столбец
## - все строки и столбцы в обратном порядке
## - второй столбец
## - третья строка

In [6]:
a = np.random.randint(10, size=(3, 4))
print(a)

[[0 4 2 4]
 [7 1 0 6]
 [9 5 2 8]]


In [7]:
print(a[:2, :3])

[[0 4 2]
 [7 1 0]]


In [8]:
print(a[:3, 1])

[4 1 5]


In [9]:
print(a[::-1, ::-1])

[[8 2 5 9]
 [6 0 1 7]
 [4 2 4 0]]


In [10]:
print(a[:, 1])

[4 1 5]


In [11]:
print(a[2, :])

[9 5 2 8]


## 8. Продемонстрируйте, как сделать срез-копию

In [12]:
b = a[:2, :3].copy()
b[0, 0] = 100
print(b)
print(a[:2, :3])

[[100   4   2]
 [  7   1   0]]
[[0 4 2]
 [7 1 0]]


## 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки


In [13]:
a = np.array([1, 2, 3])
print(a[np.newaxis, :])
print(a[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


## 10. Разберитесь, как работает метод dstack

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dstack([a, b]))

[[[1 4]
  [2 5]
  [3 6]]]


## 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.split(a, 3))
print(np.vsplit(a, 3))
print(np.hsplit(a, 3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [16]:
a = np.dstack([a, a, a])
print(np.dsplit(a, 3))

[array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]]), array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]]), array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])]


## 12. Привести пример использования всех универсальных функций, которые я привел

In [17]:
print(a - 5)

[[[-4 -4 -4]
  [-3 -3 -3]
  [-2 -2 -2]]

 [[-1 -1 -1]
  [ 0  0  0]
  [ 1  1  1]]

 [[ 2  2  2]
  [ 3  3  3]
  [ 4  4  4]]]


In [18]:
a = np.random.randint(10, size=(3, 3))
print(a)

[[5 4 6]
 [9 5 3]
 [4 3 6]]


In [19]:
print(-a)

[[-5 -4 -6]
 [-9 -5 -3]
 [-4 -3 -6]]


In [20]:
print(a / 2)

[[2.5 2.  3. ]
 [4.5 2.5 1.5]
 [2.  1.5 3. ]]


In [21]:
print(a // 2)

[[2 2 3]
 [4 2 1]
 [2 1 3]]


In [22]:
print(a % 3)

[[2 1 0]
 [0 2 0]
 [1 0 0]]


In [23]:
print(a ** 2)

[[25 16 36]
 [81 25  9]
 [16  9 36]]


In [24]:
print(np.abs(a))

[[5 4 6]
 [9 5 3]
 [4 3 6]]


In [25]:
print(np.sin(a))

[[-0.95892427 -0.7568025  -0.2794155 ]
 [ 0.41211849 -0.95892427  0.14112001]
 [-0.7568025   0.14112001 -0.2794155 ]]


In [26]:
print(np.cos(a))

[[ 0.28366219 -0.65364362  0.96017029]
 [-0.91113026  0.28366219 -0.9899925 ]
 [-0.65364362 -0.9899925   0.96017029]]


In [27]:
print(np.tan(a))

[[-3.38051501  1.15782128 -0.29100619]
 [-0.45231566 -3.38051501 -0.14254654]
 [ 1.15782128 -0.14254654 -0.29100619]]


In [28]:
print(np.exp(a))

[[ 148.4131591    54.59815003  403.42879349]
 [8103.08392758  148.4131591    20.08553692]
 [  54.59815003   20.08553692  403.42879349]]


In [29]:
print(np.log(a))

[[1.60943791 1.38629436 1.79175947]
 [2.19722458 1.60943791 1.09861229]
 [1.38629436 1.09861229 1.79175947]]


In [30]:
print(np.log10(a))

[[0.69897    0.60205999 0.77815125]
 [0.95424251 0.69897    0.47712125]
 [0.60205999 0.47712125 0.77815125]]


In [31]:
print(np.log2(a))

[[2.32192809 2.         2.5849625 ]
 [3.169925   2.32192809 1.5849625 ]
 [2.         1.5849625  2.5849625 ]]
